<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Language::firstOrCreate(['iso_639_2' => 'aar', 'iso_639_1' => 'aa', 'name' => 'Afar']);
        Language::firstOrCreate(['iso_639_2' => 'abk', 'iso_639_1' => 'ab', 'name' => 'Abkhazian']);
        Language::firstOrCreate(['iso_639_2' => 'ace', 'iso_639_1' => '', 'name' => 'Achinese']);
        Language::firstOrCreate(['iso_639_2' => 'ach', 'iso_639_1' => '', 'name' => 'Acoli']);
        Language::firstOrCreate(['iso_639_2' => 'ada', 'iso_639_1' => '', 'name' => 'Adangme']);
        Language::firstOrCreate(['iso_639_2' => 'ady', 'iso_639_1' => '', 'name' => 'Adyghe / Adygei']);
        Language::firstOrCreate(['iso_639_2' => 'afa', 'iso_639_1' => '', 'name' => 'Afro-Asiatic languages']);
        Language::firstOrCreate(['iso_639_2' => 'afh', 'iso_639_1' => '', 'name' => 'Afrihili']);
        Language::firstOrCreate(['iso_639_2' => 'afr', 'iso_639_1' => 'af', 'name' => 'Afrikaans']);
        Language::firstOrCreate(['iso_639_2' => 'ain', 'iso_639_1' => '', 'name' => 'Ainu']);
        Language::firstOrCreate(['iso_639_2' => 'aka', 'iso_639_1' => '', 'name' => 'Akan']);
        Language::firstOrCreate(['iso_639_2' => 'akk', 'iso_639_1' => '', 'name' => 'Akkadian']);
        Language::firstOrCreate(['iso_639_2' => 'alb', 'iso_639_1' => 'sq', 'name' => 'Albanian']);
        Language::firstOrCreate(['iso_639_2' => 'sqi', 'iso_639_1' => 'sq', 'name' => 'Albanian']);
        Language::firstOrCreate(['iso_639_2' => 'ale', 'iso_639_1' => '', 'name' => 'Aleut']);
        Language::firstOrCreate(['iso_639_2' => 'alg', 'iso_639_1' => '', 'name' => 'Algonquian languages']);
        Language::firstOrCreate(['iso_639_2' => 'alt', 'iso_639_1' => '', 'name' => 'Southern Altai']);
        Language::firstOrCreate(['iso_639_2' => 'amh', 'iso_639_1' => 'am', 'name' => 'Amharic']);
        Language::firstOrCreate(['iso_639_2' => 'ang', 'iso_639_1' => '', 'name' => 'English, Old (ca.450-1100)']);
        Language::firstOrCreate(['iso_639_2' => 'anp', 'iso_639_1' => '', 'name' => 'Angika']);
        Language::firstOrCreate(['iso_639_2' => 'apa', 'iso_639_1' => '', 'name' => 'Apache languages']);
        Language::firstOrCreate(['iso_639_2' => 'ara', 'iso_639_1' => 'ar', 'name' => 'Arabic']);
        Language::firstOrCreate(['iso_639_2' => 'arc', 'iso_639_1' => '', 'name' => 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)']);
        Language::firstOrCreate(['iso_639_2' => 'arg', 'iso_639_1' => 'an', 'name' => 'Aragonese']);
        Language::firstOrCreate(['iso_639_2' => 'arm', 'iso_639_1' => 'hy', 'name' => 'Armenian']);
        Language::firstOrCreate(['iso_639_2' => 'hye', 'iso_639_1' => 'hy', 'name' => 'Armenian']);
        Language::firstOrCreate(['iso_639_2' => 'arn', 'iso_639_1' => '', 'name' => 'Mapudungun / Mapuche']);
        Language::firstOrCreate(['iso_639_2' => 'arp', 'iso_639_1' => '', 'name' => 'Arapaho']);
        Language::firstOrCreate(['iso_639_2' => 'art','iso_639_1' => '', 'name' => 'Artificial languages']);
        Language::firstOrCreate(['iso_639_2' => 'arw','iso_639_1' => '', 'name' => 'Arawak']);
        Language::firstOrCreate(['iso_639_2' => 'asm','iso_639_1' => 'as', 'name' => 'Assamese']);
        Language::firstOrCreate(['iso_639_2' => 'ast','iso_639_1' => '', 'name' => 'Asturian; Bable; Leonese; Asturleonese']);
        Language::firstOrCreate(['iso_639_2' => 'ath','iso_639_1' => '', 'name' => 'Athapascan languages']);
        Language::firstOrCreate(['iso_639_2' => 'aus','iso_639_1' => '', 'name' => 'Australian languages']);
        Language::firstOrCreate(['iso_639_2' => 'ava','iso_639_1' => 'av', 'name' => 'Avaric']);
        Language::firstOrCreate(['iso_639_2' => 'ave','iso_639_1' => 'ae', 'name' => 'Avestan']);
        Language::firstOrCreate(['iso_639_2' => 'awa','iso_639_1' => '', 'name' => 'Awadhi']);
        Language::firstOrCreate(['iso_639_2' => 'aym','iso_639_1' => 'ay', 'name' => 'Aymara']);
        Language::firstOrCreate(['iso_639_2' => 'aze','iso_639_1' => 'az', 'name' => 'Azerbaijani']);
        Language::firstOrCreate(['iso_639_2' => 'bad','iso_639_1' => '', 'name' => 'Banda languages']);
        Language::firstOrCreate(['iso_639_2' => 'bai','iso_639_1' => '', 'name' => 'Bamileke languages']);
        Language::firstOrCreate(['iso_639_2' => 'bak','iso_639_1' => 'ba', 'name' => 'Bashkir']);
        Language::firstOrCreate(['iso_639_2' => 'bal','iso_639_1' => '', 'name' => 'Baluchi']);
        Language::firstOrCreate(['iso_639_2' => 'bam','iso_639_1' => 'bm', 'name' => 'Bambara']);
        Language::firstOrCreate(['iso_639_2' => 'ban','iso_639_1' => '', 'name' => 'Balinese']);
        Language::firstOrCreate(['iso_639_2' => 'baq','iso_639_1' => 'eu', 'name' => 'Basque']);
        Language::firstOrCreate(['iso_639_2' => 'eus','iso_639_1' => 'eu', 'name' => 'Basque']);
        Language::firstOrCreate(['iso_639_2' => 'bas','iso_639_1' => '', 'name' => 'Basa']);
        Language::firstOrCreate(['iso_639_2' => 'bat','iso_639_1' => '', 'name' => 'Baltic languages']);
        Language::firstOrCreate(['iso_639_2' => 'bej','iso_639_1' => '', 'name' => 'Beja; Bedawiyet']);
        Language::firstOrCreate(['iso_639_2' => 'bel','iso_639_1' => 'be', 'name' => 'Belarusian']);
        Language::firstOrCreate(['iso_639_2' => 'bem','iso_639_1' => '', 'name' => 'Bemba']);
        Language::firstOrCreate(['iso_639_2' => 'ben','iso_639_1' => 'bn', 'name' => 'Bengali']);
        Language::firstOrCreate(['iso_639_2' => 'ber','iso_639_1' => '', 'name' => 'Berber languages']);
        Language::firstOrCreate(['iso_639_2' => 'bho','iso_639_1' => '', 'name' => 'Bhojpuri']);
        Language::firstOrCreate(['iso_639_2' => 'bih','iso_639_1' => 'bh', 'name' => 'Bihari languages']);
        Language::firstOrCreate(['iso_639_2' => 'bik','iso_639_1' => '', 'name' => 'Bikol']);
        Language::firstOrCreate(['iso_639_2' => 'bin','iso_639_1' => '', 'name' => 'Bini; Edo']);
        Language::firstOrCreate(['iso_639_2' => 'bis','iso_639_1' => 'bi', 'name' => 'Bislama']);
        Language::firstOrCreate(['iso_639_2' => 'bla','iso_639_1' => '', 'name' => 'Siksika']);
        Language::firstOrCreate(['iso_639_2' => 'bnt','iso_639_1' => '', 'name' => 'Bantu languages']);
        Language::firstOrCreate(['iso_639_2' => 'tib','iso_639_1' => 'bo', 'name' => 'Tibetan']);
        Language::firstOrCreate(['iso_639_2' => 'bod','iso_639_1' => 'bo', 'name' => 'Tibetan']);
        Language::firstOrCreate(['iso_639_2' => 'bos','iso_639_1' => 'bs', 'name' => 'Bosnian']);
        Language::firstOrCreate(['iso_639_2' => 'bra','iso_639_1' => '', 'name' => 'Braj']);
        Language::firstOrCreate(['iso_639_2' => 'bre','iso_639_1' => 'br', 'name' => 'Breton']);
        Language::firstOrCreate(['iso_639_2' => 'btk','iso_639_1' => '', 'name' => 'Batak languages']);
        Language::firstOrCreate(['iso_639_2' => 'bua','iso_639_1' => '', 'name' => 'Buriat']);
        Language::firstOrCreate(['iso_639_2' => 'bug','iso_639_1' => '', 'name' => 'Buginese']);
        Language::firstOrCreate(['iso_639_2' => 'bul','iso_639_1' => 'bg', 'name' => 'Bulgarian']);
        Language::firstOrCreate(['iso_639_2' => 'bur','iso_639_1' => 'my', 'name' => 'Burmese']);
        Language::firstOrCreate(['iso_639_2' => 'mya','iso_639_1' => 'my', 'name' => 'Burmese']);
        Language::firstOrCreate(['iso_639_2' => 'byn','iso_639_1' => '', 'name' => 'Blin; Bilin']);
        Language::firstOrCreate(['iso_639_2' => 'cad','iso_639_1' => '', 'name' => 'Caddo']);
        Language::firstOrCreate(['iso_639_2' => 'cai','iso_639_1' => '', 'name' => 'Central American Indian languages']);
        Language::firstOrCreate(['iso_639_2' => 'car','iso_639_1' => '', 'name' => 'Galibi Carib']);
        Language::firstOrCreate(['iso_639_2' => 'cat','iso_639_1' => 'ca', 'name' => 'Catalan; Valencian']);
        Language::firstOrCreate(['iso_639_2' => 'cau','iso_639_1' => '', 'name' => 'Caucasian languages']);
        Language::firstOrCreate(['iso_639_2' => 'ceb','iso_639_1' => '', 'name' => 'Cebuano']);
        Language::firstOrCreate(['iso_639_2' => 'cel','iso_639_1' => '', 'name' => 'Celtic languages']);
        Language::firstOrCreate(['iso_639_2' => 'cze','iso_639_1' => 'cs', 'name' => 'Czech']);
        Language::firstOrCreate(['iso_639_2' => 'ces','iso_639_1' => 'cs', 'name' => 'Czech']);
        Language::firstOrCreate(['iso_639_2' => 'cha','iso_639_1' => 'ch', 'name' => 'Chamorro']);
        Language::firstOrCreate(['iso_639_2' => 'chb','iso_639_1' => '', 'name' => 'Chibcha']);
        Language::firstOrCreate(['iso_639_2' => 'che','iso_639_1' => 'ce', 'name' => 'Chechen']);
        Language::firstOrCreate(['iso_639_2' => 'chg','iso_639_1' => '', 'name' => 'Chagatai']);
        Language::firstOrCreate(['iso_639_2' => 'chi','iso_639_1' => 'zh', 'name' => 'Chinese']);
        Language::firstOrCreate(['iso_639_2' => 'zho','iso_639_1' => 'zh', 'name' => 'Chinese']);
        Language::firstOrCreate(['iso_639_2' => 'chk','iso_639_1' => '', 'name' => 'Chuukese']);
        Language::firstOrCreate(['iso_639_2' => 'chm','iso_639_1' => '', 'name' => 'Mari']);
        Language::firstOrCreate(['iso_639_2' => 'chn','iso_639_1' => '', 'name' => 'Chinook jargon']);
        Language::firstOrCreate(['iso_639_2' => 'cho','iso_639_1' => '', 'name' => 'Choctaw']);
        Language::firstOrCreate(['iso_639_2' => 'chp','iso_639_1' => '', 'name' => 'Chipewyan; Dene Suline']);
        Language::firstOrCreate(['iso_639_2' => 'chr','iso_639_1' => '', 'name' => 'Cherokee']);
        Language::firstOrCreate(['iso_639_2' => 'chu','iso_639_1' => 'cu', 'name' => 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic']);
        Language::firstOrCreate(['iso_639_2' => 'chv','iso_639_1' => 'cv', 'name' => 'Chuvash']);
        Language::firstOrCreate(['iso_639_2' => 'chy','iso_639_1' => '', 'name' => 'Cheyenne']);
        Language::firstOrCreate(['iso_639_2' => 'cmc','iso_639_1' => '', 'name' => 'Chamic languages']);
        Language::firstOrCreate(['iso_639_2' => 'cnr','iso_639_1' => '', 'name' => 'Montenegrin']);
        Language::firstOrCreate(['iso_639_2' => 'cop','iso_639_1' => '', 'name' => 'Coptic']);
        Language::firstOrCreate(['iso_639_2' => 'cor','iso_639_1' => 'kw', 'name' => 'Cornish']);
        Language::firstOrCreate(['iso_639_2' => 'cos','iso_639_1' => 'co', 'name' => 'Corsican']);
        Language::firstOrCreate(['iso_639_2' => 'cpe','iso_639_1' => '', 'name' => 'Creoles and pidgins, English based']);
        Language::firstOrCreate(['iso_639_2' => 'cpf','iso_639_1' => '', 'name' => 'Creoles and pidgins, French-based']);
        Language::firstOrCreate(['iso_639_2' => 'cpp','iso_639_1' => '', 'name' => 'Creoles and pidgins, Portuguese-based']);
        Language::firstOrCreate(['iso_639_2' => 'cre','iso_639_1' => 'cr', 'name' => 'Cree']);
        Language::firstOrCreate(['iso_639_2' => 'crh','iso_639_1' => '', 'name' => 'Crimean Tatar; Crimean Turkish']);
        Language::firstOrCreate(['iso_639_2' => 'crp','iso_639_1' => '', 'name' => 'Creoles and pidgins']);
        Language::firstOrCreate(['iso_639_2' => 'csb','iso_639_1' => '', 'name' => 'Kashubian']);
        Language::firstOrCreate(['iso_639_2' => 'cus','iso_639_1' => '', 'name' => 'Cushitic languages']);
        Language::firstOrCreate(['iso_639_2' => 'wel','iso_639_1' => 'cy', 'name' => 'Welsh']);
        Language::firstOrCreate(['iso_639_2' => 'cym','iso_639_1' => 'cy', 'name' => 'Welsh']);
        Language::firstOrCreate(['iso_639_2' => 'cze','iso_639_1' => 'cs', 'name' => 'Czech']);
        Language::firstOrCreate(['iso_639_2' => 'ces','iso_639_1' => 'cs', 'name' => 'Czech']);
        Language::firstOrCreate(['iso_639_2' => 'dak','iso_639_1' => '', 'name' => 'Dakota']);
        Language::firstOrCreate(['iso_639_2' => 'dan','iso_639_1' => 'da', 'name' => 'Danish']);
        Language::firstOrCreate(['iso_639_2' => 'dar','iso_639_1' => '', 'name' => 'Dargwa']);
        Language::firstOrCreate(['iso_639_2' => 'day','iso_639_1' => '', 'name' => 'Land Dayak languages']);
        Language::firstOrCreate(['iso_639_2' => 'del','iso_639_1' => '', 'name' => 'Delaware']);
        Language::firstOrCreate(['iso_639_2' => 'den','iso_639_1' => '', 'name' => 'Slave (Athapascan)']);
        Language::firstOrCreate(['iso_639_2' => 'ger','iso_639_1' => 'de', 'name' => 'German']);
        Language::firstOrCreate(['iso_639_2' => 'deu','iso_639_1' => 'de', 'name' => 'German']);
        Language::firstOrCreate(['iso_639_2' => 'dgr','iso_639_1' => '', 'name' => 'Dogrib']);
        Language::firstOrCreate(['iso_639_2' => 'din','iso_639_1' => '', 'name' => 'Dinka']);
        Language::firstOrCreate(['iso_639_2' => 'div','iso_639_1' => 'dv', 'name' => 'Divehi; Dhivehi; Maldivian']);
        Language::firstOrCreate(['iso_639_2' => 'doi','iso_639_1' => '', 'name' => 'Dogri']);
        Language::firstOrCreate(['iso_639_2' => 'dra','iso_639_1' => '', 'name' => 'Dravidian languages']);
        Language::firstOrCreate(['iso_639_2' => 'dsb','iso_639_1' => '', 'name' => 'Lower Sorbian']);
        Language::firstOrCreate(['iso_639_2' => 'dua','iso_639_1' => '', 'name' => 'Duala']);
        Language::firstOrCreate(['iso_639_2' => 'dum','iso_639_1' => '', 'name' => 'Dutch, Middle (ca.1050-1350)']);
        Language::firstOrCreate(['iso_639_2' => 'dut','iso_639_1' => 'nl', 'name' => 'Dutch; Flemish']);
        Language::firstOrCreate(['iso_639_2' => 'nld','iso_639_1' => 'nl', 'name' => 'Dutch; Flemish']);
        Language::firstOrCreate(['iso_639_2' => 'dyu','iso_639_1' => '', 'name' => 'Dyula']);
        Language::firstOrCreate(['iso_639_2' => 'dzo','iso_639_1' => 'dz', 'name' => 'Dzongkha']);
        Language::firstOrCreate(['iso_639_2' => 'efi','iso_639_1' => '', 'name' => 'Efik']);
        Language::firstOrCreate(['iso_639_2' => 'egy','iso_639_1' => '', 'name' => 'Egyptian (Ancient)']);
        Language::firstOrCreate(['iso_639_2' => 'eka','iso_639_1' => '', 'name' => 'Ekajuk']);
        Language::firstOrCreate(['iso_639_2' => 'gre','iso_639_1' => 'el', 'name' => 'Greek, Modern (1453-)']);
        Language::firstOrCreate(['iso_639_2' => 'ell','iso_639_1' => 'el', 'name' => 'Greek, Modern (1453-)']);
        Language::firstOrCreate(['iso_639_2' => 'elx','iso_639_1' => '', 'name' => 'Elamite']);
        Language::firstOrCreate(['iso_639_2' => 'eng','iso_639_1' => 'en', 'name' => 'English']);
        Language::firstOrCreate(['iso_639_2' => 'enm','iso_639_1' => '', 'name' => 'English, Middle (1100-1500)']);
        Language::firstOrCreate(['iso_639_2' => 'epo','iso_639_1' => 'eo', 'name' => 'Esperanto']);
        Language::firstOrCreate(['iso_639_2' => 'est','iso_639_1' => 'et', 'name' => 'Estonian']);
        Language::firstOrCreate(['iso_639_2' => 'baq','iso_639_1' => 'eu', 'name' => 'Basque']);
        Language::firstOrCreate(['iso_639_2' => 'eus','iso_639_1' => 'eu', 'name' => 'Basque']);
        Language::firstOrCreate(['iso_639_2' => 'ewe','iso_639_1' => 'ee', 'name' => 'Ewe']);
        Language::firstOrCreate(['iso_639_2' => 'ewo','iso_639_1' => '', 'name' => 'Ewondo']);
        Language::firstOrCreate(['iso_639_2' => 'fan','iso_639_1' => '', 'name' => 'Fang']);
        Language::firstOrCreate(['iso_639_2' => 'fao','iso_639_1' => 'fo', 'name' => 'Faroese']);
        Language::firstOrCreate(['iso_639_2' => 'per','iso_639_1' => 'fa', 'name' => 'Persian']);
        Language::firstOrCreate(['iso_639_2' => 'fas','iso_639_1' => 'fa', 'name' => 'Persian']);
        Language::firstOrCreate(['iso_639_2' => 'fat','iso_639_1' => '', 'name' => 'Fanti']);
        Language::firstOrCreate(['iso_639_2' => 'fij','iso_639_1' => 'fj', 'name' => 'Fijian']);
        Language::firstOrCreate(['iso_639_2' => 'fil','iso_639_1' => '', 'name' => 'Filipino; Pilipino']);
        Language::firstOrCreate(['iso_639_2' => 'fin','iso_639_1' => 'fi', 'name' => 'Finnish']);
        Language::firstOrCreate(['iso_639_2' => 'fiu','iso_639_1' => '', 'name' => 'Finno-Ugrian languages']);
        Language::firstOrCreate(['iso_639_2' => 'fon','iso_639_1' => '', 'name' => 'Fon']);
        Language::firstOrCreate(['iso_639_2' => 'fre','iso_639_1' => 'fr', 'name' => 'French']);
        Language::firstOrCreate(['iso_639_2' => 'fra','iso_639_1' => 'fr', 'name' => 'French']);
        Language::firstOrCreate(['iso_639_2' => 'frm','iso_639_1' => '', 'name' => 'French, Middle (ca.1400-1600)']);
        Language::firstOrCreate(['iso_639_2' => 'fro','iso_639_1' => '', 'name' => 'French, Old (842-ca.1400)']);
        Language::firstOrCreate(['iso_639_2' => 'frr','iso_639_1' => '', 'name' => 'Northern Frisian']);
        Language::firstOrCreate(['iso_639_2' => 'frs','iso_639_1' => '', 'name' => 'Eastern Frisian']);
        Language::firstOrCreate(['iso_639_2' => 'fry','iso_639_1' => 'fy', 'name' => 'Western Frisian']);
        Language::firstOrCreate(['iso_639_2' => 'ful','iso_639_1' => 'ff', 'name' => 'Fulah']);
        Language::firstOrCreate(['iso_639_2' => 'fur','iso_639_1' => '', 'name' => 'Friulian']);
        Language::firstOrCreate(['iso_639_2' => 'gaa','iso_639_1' => '', 'name' => 'Ga']);
        Language::firstOrCreate(['iso_639_2' => 'gay','iso_639_1' => '', 'name' => 'Gayo']);
        Language::firstOrCreate(['iso_639_2' => 'gba','iso_639_1' => '', 'name' => 'Gbaya']);
        Language::firstOrCreate(['iso_639_2' => 'gem','iso_639_1' => '', 'name' => 'Germanic languages']);
        Language::firstOrCreate(['iso_639_2' => 'geo','iso_639_1' => 'ka', 'name' => 'Georgian']);
        Language::firstOrCreate(['iso_639_2' => 'kat','iso_639_1' => 'ka', 'name' => 'Georgian']);
        Language::firstOrCreate(['iso_639_2' => 'ger','iso_639_1' => 'de', 'name' => 'German']);
        Language::firstOrCreate(['iso_639_2' => 'deu','iso_639_1' => 'de', 'name' => 'German']);
        Language::firstOrCreate(['iso_639_2' => 'gez','iso_639_1' => '', 'name' => 'Geez']);
        Language::firstOrCreate(['iso_639_2' => 'gil','iso_639_1' => '', 'name' => 'Gilbertese']);
        Language::firstOrCreate(['iso_639_2' => 'gla','iso_639_1' => 'gd', 'name' => 'Gaelic; Scottish Gaelic']);
        Language::firstOrCreate(['iso_639_2' => 'gle','iso_639_1' => 'ga', 'name' => 'Irish']);
        Language::firstOrCreate(['iso_639_2' => 'glg','iso_639_1' => 'gl', 'name' => 'Galician']);
        Language::firstOrCreate(['iso_639_2' => 'glv','iso_639_1' => 'gv', 'name' => 'Manx']);
        Language::firstOrCreate(['iso_639_2' => 'gmh','iso_639_1' => '', 'name' => 'German, Middle High (ca.1050-1500)']);
        Language::firstOrCreate(['iso_639_2' => 'goh','iso_639_1' => '', 'name' => 'German, Old High (ca.750-1050)']);
        Language::firstOrCreate(['iso_639_2' => 'gon','iso_639_1' => '', 'name' => 'Gondi']);
        Language::firstOrCreate(['iso_639_2' => 'gor','iso_639_1' => '', 'name' => 'Gorontalo']);
        Language::firstOrCreate(['iso_639_2' => 'got','iso_639_1' => '', 'name' => 'Gothic']);
        Language::firstOrCreate(['iso_639_2' => 'grb','iso_639_1' => '', 'name' => 'Grebo']);
        Language::firstOrCreate(['iso_639_2' => 'grc','iso_639_1' => '', 'name' => 'Greek, Ancient (to 1453)']);
        Language::firstOrCreate(['iso_639_2' => 'gre','iso_639_1' => 'el', 'name' => 'Greek, Modern (1453-)']);
        Language::firstOrCreate(['iso_639_2' => 'ell','iso_639_1' => 'el', 'name' => 'Greek, Modern (1453-)']);
        Language::firstOrCreate(['iso_639_2' => 'grn','iso_639_1' => 'gn', 'name' => 'Guarani']);
        Language::firstOrCreate(['iso_639_2' => 'gsw','iso_639_1' => '', 'name' => 'Swiss German; Alemannic; Alsatian']);
        Language::firstOrCreate(['iso_639_2' => 'guj','iso_639_1' => 'gu', 'name' => 'Gujarati']);
        Language::firstOrCreate(['iso_639_2' => 'gwi','iso_639_1' => '', 'name' => 'Gwich\'in']);
        Language::firstOrCreate(['iso_639_2' => 'hai','iso_639_1' => '', 'name' => 'Haida']);
        Language::firstOrCreate(['iso_639_2' => 'hat','iso_639_1' => 'ht', 'name' => 'Haitian; Haitian Creole']);
        Language::firstOrCreate(['iso_639_2' => 'hau','iso_639_1' => 'ha', 'name' => 'Hausa']);
        Language::firstOrCreate(['iso_639_2' => 'haw','iso_639_1' => '', 'name' => 'Hawaiian']);
        Language::firstOrCreate(['iso_639_2' => 'heb','iso_639_1' => 'he', 'name' => 'Hebrew']);
        Language::firstOrCreate(['iso_639_2' => 'her','iso_639_1' => 'hz', 'name' => 'Herero']);
        Language::firstOrCreate(['iso_639_2' => 'hil','iso_639_1' => '', 'name' => 'Hiligaynon']);
        Language::firstOrCreate(['iso_639_2' => 'him','iso_639_1' => '', 'name' => 'Himachali languages; Western Pahari languages']);
        Language::firstOrCreate(['iso_639_2' => 'hin','iso_639_1' => 'hi', 'name' => 'Hindi']);
        Language::firstOrCreate(['iso_639_2' => 'hit','iso_639_1' => '', 'name' => 'Hittite']);
        Language::firstOrCreate(['iso_639_2' => 'hmn','iso_639_1' => '', 'name' => 'Hmong; Mong']);
        Language::firstOrCreate(['iso_639_2' => 'hmo','iso_639_1' => 'ho', 'name' => 'Hiri Motu']);
        Language::firstOrCreate(['iso_639_2' => 'hrv','iso_639_1' => 'hr', 'name' => 'Croatian']);
        Language::firstOrCreate(['iso_639_2' => 'hsb','iso_639_1' => '', 'name' => 'Upper Sorbian']);
        Language::firstOrCreate(['iso_639_2' => 'hun','iso_639_1' => 'hu', 'name' => 'Hungarian']);
        Language::firstOrCreate(['iso_639_2' => 'hup','iso_639_1' => '', 'name' => 'Hupa']);
        Language::firstOrCreate(['iso_639_2' => 'arm','iso_639_1' => 'hy', 'name' => 'Armenian']);
        Language::firstOrCreate(['iso_639_2' => 'hye','iso_639_1' => 'hy', 'name' => 'Armenian']);
        Language::firstOrCreate(['iso_639_2' => 'iba','iso_639_1' => '', 'name' => 'Iban']);
        Language::firstOrCreate(['iso_639_2' => 'ibo','iso_639_1' => 'ig', 'name' => 'Igbo']);
        Language::firstOrCreate(['iso_639_2' => 'ice','iso_639_1' => 'is', 'name' => 'Icelandic']);
        Language::firstOrCreate(['iso_639_2' => 'isl','iso_639_1' => 'is', 'name' => 'Icelandic']);
        Language::firstOrCreate(['iso_639_2' => 'ido','iso_639_1' => 'io', 'name' => 'Ido']);
        Language::firstOrCreate(['iso_639_2' => 'iii','iso_639_1' => 'ii', 'name' => 'Sichuan Yi; Nuosu']);
        Language::firstOrCreate(['iso_639_2' => 'ijo','iso_639_1' => '', 'name' => 'Ijo languages']);
        Language::firstOrCreate(['iso_639_2' => 'iku','iso_639_1' => 'iu', 'name' => 'Inuktitut']);
        Language::firstOrCreate(['iso_639_2' => 'ile','iso_639_1' => 'ie', 'name' => 'Interlingue; Occidental']);
        Language::firstOrCreate(['iso_639_2' => 'ilo','iso_639_1' => '', 'name' => 'Iloko']);
        Language::firstOrCreate(['iso_639_2' => 'ina','iso_639_1' => 'ia', 'name' => 'Interlingua (International Auxiliary Language Association)']);
        Language::firstOrCreate(['iso_639_2' => 'inc','iso_639_1' => '', 'name' => 'Indic languages']);
        Language::firstOrCreate(['iso_639_2' => 'ind','iso_639_1' => 'id', 'name' => 'Indonesian']);
        Language::firstOrCreate(['iso_639_2' => 'ine','iso_639_1' => '', 'name' => 'Indo-European languages']);
        Language::firstOrCreate(['iso_639_2' => 'inh','iso_639_1' => '', 'name' => 'Ingush']);
        Language::firstOrCreate(['iso_639_2' => 'ipk','iso_639_1' => 'ik', 'name' => 'Inupiaq']);
        Language::firstOrCreate(['iso_639_2' => 'ira','iso_639_1' => '', 'name' => 'Iranian languages']);
        Language::firstOrCreate(['iso_639_2' => 'iro','iso_639_1' => '', 'name' => 'Iroquoian languages']);
        Language::firstOrCreate(['iso_639_2' => 'ice','iso_639_1' => 'is', 'name' => 'Icelandic']);
        Language::firstOrCreate(['iso_639_2' => 'isl','iso_639_1' => 'is', 'name' => 'Icelandic']);
        Language::firstOrCreate(['iso_639_2' => 'ita','iso_639_1' => 'it', 'name' => 'Italian']);
        Language::firstOrCreate(['iso_639_2' => 'jav','iso_639_1' => 'jv', 'name' => 'Javanese']);
        Language::firstOrCreate(['iso_639_2' => 'jbo','iso_639_1' => '', 'name' => 'Lojban']);
        Language::firstOrCreate(['iso_639_2' => 'jpn','iso_639_1' => 'ja', 'name' => 'Japanese']);
        Language::firstOrCreate(['iso_639_2' => 'jpr','iso_639_1' => '', 'name' => 'Judeo-Persian']);
        Language::firstOrCreate(['iso_639_2' => 'jrb','iso_639_1' => '', 'name' => 'Judeo-Arabic']);
        Language::firstOrCreate(['iso_639_2' => 'kaa','iso_639_1' => '', 'name' => 'Kara-Kalpak']);
        Language::firstOrCreate(['iso_639_2' => 'kab','iso_639_1' => '', 'name' => 'Kabyle']);
        Language::firstOrCreate(['iso_639_2' => 'kac','iso_639_1' => '', 'name' => 'Kachin; Jingpho']);
        Language::firstOrCreate(['iso_639_2' => 'kal','iso_639_1' => 'kl', 'name' => 'Kalaallisut; Greenlandic']);
        Language::firstOrCreate(['iso_639_2' => 'kam','iso_639_1' => '', 'name' => 'Kamba']);
        Language::firstOrCreate(['iso_639_2' => 'kan','iso_639_1' => 'kn', 'name' => 'Kannada']);
        Language::firstOrCreate(['iso_639_2' => 'kar','iso_639_1' => '', 'name' => 'Karen languages']);
        Language::firstOrCreate(['iso_639_2' => 'kas','iso_639_1' => 'ks', 'name' => 'Kashmiri']);
        Language::firstOrCreate(['iso_639_2' => 'geo','iso_639_1' => 'ka', 'name' => 'Georgian']);
        Language::firstOrCreate(['iso_639_2' => 'kat','iso_639_1' => 'ka', 'name' => 'Georgian']);
        Language::firstOrCreate(['iso_639_2' => 'kau','iso_639_1' => 'kr', 'name' => 'Kanuri']);
        Language::firstOrCreate(['iso_639_2' => 'kaw','iso_639_1' => '', 'name' => 'Kawi']);
        Language::firstOrCreate(['iso_639_2' => 'kaz','iso_639_1' => 'kk', 'name' => 'Kazakh']);
        Language::firstOrCreate(['iso_639_2' => 'kbd','iso_639_1' => '', 'name' => 'Kabardian']);
        Language::firstOrCreate(['iso_639_2' => 'kha','iso_639_1' => '', 'name' => 'Khasi']);
        Language::firstOrCreate(['iso_639_2' => 'khi','iso_639_1' => '', 'name' => 'Khoisan languages']);
        Language::firstOrCreate(['iso_639_2' => 'khm','iso_639_1' => 'km', 'name' => 'Central Khmer']);
        Language::firstOrCreate(['iso_639_2' => 'kho','iso_639_1' => '', 'name' => 'Khotanese; Sakan']);
        Language::firstOrCreate(['iso_639_2' => 'kik','iso_639_1' => 'ki', 'name' => 'Kikuyu; Gikuyu']);
        Language::firstOrCreate(['iso_639_2' => 'kin','iso_639_1' => 'rw', 'name' => 'Kinyarwanda']);
        Language::firstOrCreate(['iso_639_2' => 'kir','iso_639_1' => 'ky', 'name' => 'Kirghiz; Kyrgyz']);
        Language::firstOrCreate(['iso_639_2' => 'kmb','iso_639_1' => '', 'name' => 'Kimbundu']);
        Language::firstOrCreate(['iso_639_2' => 'kok','iso_639_1' => '', 'name' => 'Konkani']);
        Language::firstOrCreate(['iso_639_2' => 'kom','iso_639_1' => 'kv', 'name' => 'Komi']);
        Language::firstOrCreate(['iso_639_2' => 'kon','iso_639_1' => 'kg', 'name' => 'Kongo']);
        Language::firstOrCreate(['iso_639_2' => 'kor','iso_639_1' => 'ko', 'name' => 'Korean']);
        Language::firstOrCreate(['iso_639_2' => 'kos','iso_639_1' => '', 'name' => 'Kosraean']);
        Language::firstOrCreate(['iso_639_2' => 'kpe','iso_639_1' => '', 'name' => 'Kpelle']);
        Language::firstOrCreate(['iso_639_2' => 'krc','iso_639_1' => '', 'name' => 'Karachay-Balkar']);
        Language::firstOrCreate(['iso_639_2' => 'krl','iso_639_1' => '', 'name' => 'Karelian']);
        Language::firstOrCreate(['iso_639_2' => 'kro','iso_639_1' => '', 'name' => 'Kru languages']);
        Language::firstOrCreate(['iso_639_2' => 'kru','iso_639_1' => '', 'name' => 'Kurukh']);
        Language::firstOrCreate(['iso_639_2' => 'kua','iso_639_1' => 'kj', 'name' => 'Kuanyama; Kwanyama']);
        Language::firstOrCreate(['iso_639_2' => 'kum','iso_639_1' => '', 'name' => 'Kumyk']);
        Language::firstOrCreate(['iso_639_2' => 'kur','iso_639_1' => 'ku', 'name' => 'Kurdish']);
        Language::firstOrCreate(['iso_639_2' => 'kut','iso_639_1' => '', 'name' => 'Kutenai']);
        Language::firstOrCreate(['iso_639_2' => 'lad','iso_639_1' => '', 'name' => 'Ladino']);
        Language::firstOrCreate(['iso_639_2' => 'lah','iso_639_1' => '', 'name' => 'Lahnda']);
        Language::firstOrCreate(['iso_639_2' => 'lam','iso_639_1' => '', 'name' => 'Lamba']);
        Language::firstOrCreate(['iso_639_2' => 'lao','iso_639_1' => 'lo', 'name' => 'Lao']);
        Language::firstOrCreate(['iso_639_2' => 'lat','iso_639_1' => 'la', 'name' => 'Latin']);
        Language::firstOrCreate(['iso_639_2' => 'lav','iso_639_1' => 'lv', 'name' => 'Latvian']);
        Language::firstOrCreate(['iso_639_2' => 'lez','iso_639_1' => '', 'name' => 'Lezghian']);
        Language::firstOrCreate(['iso_639_2' => 'lim','iso_639_1' => 'li', 'name' => 'Limburgan; Limburger; Limburgish']);
        Language::firstOrCreate(['iso_639_2' => 'lin','iso_639_1' => 'ln', 'name' => 'Lingala']);
        Language::firstOrCreate(['iso_639_2' => 'lit','iso_639_1' => 'lt', 'name' => 'Lithuanian']);
        Language::firstOrCreate(['iso_639_2' => 'lol','iso_639_1' => '', 'name' => 'Mongo']);
        Language::firstOrCreate(['iso_639_2' => 'loz','iso_639_1' => '', 'name' => 'Lozi']);
        Language::firstOrCreate(['iso_639_2' => 'ltz','iso_639_1' => 'lb', 'name' => 'Luxembourgish; Letzeburgesch']);
        Language::firstOrCreate(['iso_639_2' => 'lua','iso_639_1' => '', 'name' => 'Luba-Lulua']);
        Language::firstOrCreate(['iso_639_2' => 'lub','iso_639_1' => 'lu', 'name' => 'Luba-Katanga']);
        Language::firstOrCreate(['iso_639_2' => 'lug','iso_639_1' => 'lg', 'name' => 'Ganda']);
        Language::firstOrCreate(['iso_639_2' => 'lui','iso_639_1' => '', 'name' => 'Luiseno']);
        Language::firstOrCreate(['iso_639_2' => 'lun','iso_639_1' => '', 'name' => 'Lunda']);
        Language::firstOrCreate(['iso_639_2' => 'luo','iso_639_1' => '', 'name' => 'Luo (Kenya and Tanzania)']);
        Language::firstOrCreate(['iso_639_2' => 'lus','iso_639_1' => '', 'name' => 'Lushai']);
        Language::firstOrCreate(['iso_639_2' => 'mac','iso_639_1' => 'mk', 'name' => 'Macedonian']);
        Language::firstOrCreate(['iso_639_2' => 'mkd','iso_639_1' => 'mk', 'name' => 'Macedonian']);
        Language::firstOrCreate(['iso_639_2' => 'mad','iso_639_1' => '', 'name' => 'Madurese']);
        Language::firstOrCreate(['iso_639_2' => 'mag','iso_639_1' => '', 'name' => 'Magahi']);
        Language::firstOrCreate(['iso_639_2' => 'mah','iso_639_1' => 'mh', 'name' => 'Marshallese']);
        Language::firstOrCreate(['iso_639_2' => 'mai','iso_639_1' => '', 'name' => 'Maithili']);
        Language::firstOrCreate(['iso_639_2' => 'mak','iso_639_1' => '', 'name' => 'Makasar']);
        Language::firstOrCreate(['iso_639_2' => 'mal','iso_639_1' => 'ml', 'name' => 'Malayalam']);
        Language::firstOrCreate(['iso_639_2' => 'man','iso_639_1' => '', 'name' => 'Mandingo']);
        Language::firstOrCreate(['iso_639_2' => 'mao','iso_639_1' => 'mi', 'name' => 'Maori']);
        Language::firstOrCreate(['iso_639_2' => 'mri','iso_639_1' => 'mi', 'name' => 'Maori']);
        Language::firstOrCreate(['iso_639_2' => 'map','iso_639_1' => '', 'name' => 'Austronesian languages']);
        Language::firstOrCreate(['iso_639_2' => 'mar','iso_639_1' => 'mr', 'name' => 'Marathi']);
        Language::firstOrCreate(['iso_639_2' => 'mas','iso_639_1' => '', 'name' => 'Masai']);
        Language::firstOrCreate(['iso_639_2' => 'May','iso_639_1' => 'ms', 'name' => 'Malay']);
        Language::firstOrCreate(['iso_639_2' => 'msa','iso_639_1' => 'ms', 'name' => 'Malay']);
        Language::firstOrCreate(['iso_639_2' => 'mdf','iso_639_1' => '', 'name' => 'Moksha']);
        Language::firstOrCreate(['iso_639_2' => 'mdr','iso_639_1' => '', 'name' => 'Mandar']);
        Language::firstOrCreate(['iso_639_2' => 'men','iso_639_1' => '', 'name' => 'Mende']);
        Language::firstOrCreate(['iso_639_2' => 'mga','iso_639_1' => '', 'name' => 'Irish, Middle (900-1200)']);
        Language::firstOrCreate(['iso_639_2' => 'mic','iso_639_1' => '', 'name' => 'Mi\'kmaq; Micmac']);
        Language::firstOrCreate(['iso_639_2' => 'min','iso_639_1' => '', 'name' => 'Minangkabau']);
        Language::firstOrCreate(['iso_639_2' => 'mis','iso_639_1' => '', 'name' => 'Uncoded languages']);
        Language::firstOrCreate(['iso_639_2' => 'mac','iso_639_1' => 'mk', 'name' => 'Macedonian']);
        Language::firstOrCreate(['iso_639_2' => 'mkd','iso_639_1' => 'mk', 'name' => 'Macedonian']);
        Language::firstOrCreate(['iso_639_2' => 'mkh','iso_639_1' => '', 'name' => 'Mon-Khmer languages']);
        Language::firstOrCreate(['iso_639_2' => 'mlg','iso_639_1' => 'mg', 'name' => 'Malagasy']);
        Language::firstOrCreate(['iso_639_2' => 'mlt','iso_639_1' => 'mt', 'name' => 'Maltese']);
        Language::firstOrCreate(['iso_639_2' => 'mnc','iso_639_1' => '', 'name' => 'Manchu']);
        Language::firstOrCreate(['iso_639_2' => 'mni','iso_639_1' => '', 'name' => 'Manipuri']);
        Language::firstOrCreate(['iso_639_2' => 'mno','iso_639_1' => '', 'name' => 'Manobo languages']);
        Language::firstOrCreate(['iso_639_2' => 'moh','iso_639_1' => '', 'name' => 'Mohawk']);
        Language::firstOrCreate(['iso_639_2' => 'mon','iso_639_1' => 'mn', 'name' => 'Mongolian']);
        Language::firstOrCreate(['iso_639_2' => 'mos','iso_639_1' => '', 'name' => 'Mossi']);
        Language::firstOrCreate(['iso_639_2' => 'mao','iso_639_1' => 'mi', 'name' => 'Maori']);
        Language::firstOrCreate(['iso_639_2' => 'mri','iso_639_1' => 'mi', 'name' => 'Maori']);
        Language::firstOrCreate(['iso_639_2' => 'May','iso_639_1' => 'ms', 'name' => 'Malay']);
        Language::firstOrCreate(['iso_639_2' => 'msa','iso_639_1' => 'ms', 'name' => 'Malay']);
        Language::firstOrCreate(['iso_639_2' => 'mul','iso_639_1' => '', 'name' => 'Multiple languages']);
        Language::firstOrCreate(['iso_639_2' => 'mun','iso_639_1' => '', 'name' => 'Munda languages']);
        Language::firstOrCreate(['iso_639_2' => 'mus','iso_639_1' => '', 'name' => 'Creek']);
        Language::firstOrCreate(['iso_639_2' => 'mwl','iso_639_1' => '', 'name' => 'Mirandese']);
        Language::firstOrCreate(['iso_639_2' => 'mwr','iso_639_1' => '', 'name' => 'Marwari']);
        Language::firstOrCreate(['iso_639_2' => 'bur','iso_639_1' => 'my', 'name' => 'Burmese']);
        Language::firstOrCreate(['iso_639_2' => 'mya','iso_639_1' => 'my', 'name' => 'Burmese']);
        Language::firstOrCreate(['iso_639_2' => 'myn','iso_639_1' => '', 'name' => 'Mayan languages']);
        Language::firstOrCreate(['iso_639_2' => 'myv','iso_639_1' => '', 'name' => 'Erzya']);
        Language::firstOrCreate(['iso_639_2' => 'nah','iso_639_1' => '', 'name' => 'Nahuatl languages']);
        Language::firstOrCreate(['iso_639_2' => 'nai','iso_639_1' => '', 'name' => 'North American Indian languages']);
        Language::firstOrCreate(['iso_639_2' => 'nap','iso_639_1' => '', 'name' => 'Neapolitan']);
        Language::firstOrCreate(['iso_639_2' => 'nau','iso_639_1' => 'na', 'name' => 'Nauru']);
        Language::firstOrCreate(['iso_639_2' => 'nav','iso_639_1' => 'nv', 'name' => 'Navajo; Navaho']);
        Language::firstOrCreate(['iso_639_2' => 'nbl','iso_639_1' => 'nr', 'name' => 'Ndebele, South; South Ndebele']);
        Language::firstOrCreate(['iso_639_2' => 'nde','iso_639_1' => 'nd', 'name' => 'Ndebele, North; North Ndebele']);
        Language::firstOrCreate(['iso_639_2' => 'ndo','iso_639_1' => 'ng', 'name' => 'Ndonga']);
        Language::firstOrCreate(['iso_639_2' => 'nds','iso_639_1' => '', 'name' => 'Low German; Low Saxon; German, Low; Saxon, Low']);
        Language::firstOrCreate(['iso_639_2' => 'nep','iso_639_1' => 'ne', 'name' => 'Nepali']);
        Language::firstOrCreate(['iso_639_2' => 'new','iso_639_1' => '', 'name' => 'Nepal Bhasa; Newari']);
        Language::firstOrCreate(['iso_639_2' => 'nia','iso_639_1' => '', 'name' => 'Nias']);
        Language::firstOrCreate(['iso_639_2' => 'nic','iso_639_1' => '', 'name' => 'Niger-Kordofanian languages']);
        Language::firstOrCreate(['iso_639_2' => 'niu','iso_639_1' => '', 'name' => 'Niuean']);
        Language::firstOrCreate(['iso_639_2' => 'dut','iso_639_1' => 'nl', 'name' => 'Dutch; Flemish']);
        Language::firstOrCreate(['iso_639_2' => 'nld','iso_639_1' => 'nl', 'name' => 'Dutch; Flemish']);
        Language::firstOrCreate(['iso_639_2' => 'nno','iso_639_1' => 'nn', 'name' => 'Norwegian Nynorsk; Nynorsk, Norwegian']);
        Language::firstOrCreate(['iso_639_2' => 'nob','iso_639_1' => 'nb', 'name' => 'Bokmal, Norwegian; Norwegian Bokmal']);
        Language::firstOrCreate(['iso_639_2' => 'nog','iso_639_1' => '', 'name' => 'Nogai']);
        Language::firstOrCreate(['iso_639_2' => 'non','iso_639_1' => '', 'name' => 'Norse, Old']);
        Language::firstOrCreate(['iso_639_2' => 'nor','iso_639_1' => 'no', 'name' => 'Norwegian']);
        Language::firstOrCreate(['iso_639_2' => 'nqo','iso_639_1' => '', 'name' => 'N\'Ko']);
        Language::firstOrCreate(['iso_639_2' => 'nso','iso_639_1' => '', 'name' => 'Pedi; Sepedi; Northern Sotho']);
        Language::firstOrCreate(['iso_639_2' => 'nub','iso_639_1' => '', 'name' => 'Nubian languages']);
        Language::firstOrCreate(['iso_639_2' => 'nwc','iso_639_1' => '', 'name' => 'Classical Newari; Old Newari; Classical Nepal Bhasa']);
        Language::firstOrCreate(['iso_639_2' => 'nya','iso_639_1' => 'ny', 'name' => 'Chichewa; Chewa; Nyanja']);
        Language::firstOrCreate(['iso_639_2' => 'nym','iso_639_1' => '', 'name' => 'Nyamwezi']);
        Language::firstOrCreate(['iso_639_2' => 'nyn','iso_639_1' => '', 'name' => 'Nyankole']);
        Language::firstOrCreate(['iso_639_2' => 'nyo','iso_639_1' => '', 'name' => 'Nyoro']);
        Language::firstOrCreate(['iso_639_2' => 'nzi','iso_639_1' => '', 'name' => 'Nzima']);
        Language::firstOrCreate(['iso_639_2' => 'oci','iso_639_1' => 'oc', 'name' => 'Occitan (post 1500)']);
        Language::firstOrCreate(['iso_639_2' => 'oji','iso_639_1' => 'oj', 'name' => 'Ojibwa']);
        Language::firstOrCreate(['iso_639_2' => 'ori','iso_639_1' => 'or', 'name' => 'Oriya']);
        Language::firstOrCreate(['iso_639_2' => 'orm','iso_639_1' => 'om', 'name' => 'Oromo']);
        Language::firstOrCreate(['iso_639_2' => 'osa','iso_639_1' => '', 'name' => 'Osage']);
        Language::firstOrCreate(['iso_639_2' => 'oss','iso_639_1' => 'os', 'name' => 'Ossetian; Ossetic']);
        Language::firstOrCreate(['iso_639_2' => 'ota','iso_639_1' => '', 'name' => 'Turkish, Ottoman (1500-1928)']);
        Language::firstOrCreate(['iso_639_2' => 'oto','iso_639_1' => '', 'name' => 'Otomian languages']);
        Language::firstOrCreate(['iso_639_2' => 'paa','iso_639_1' => '', 'name' => 'Papuan languages']);
        Language::firstOrCreate(['iso_639_2' => 'pag','iso_639_1' => '', 'name' => 'Pangasinan']);
        Language::firstOrCreate(['iso_639_2' => 'pal','iso_639_1' => '', 'name' => 'Pahlavi']);
        Language::firstOrCreate(['iso_639_2' => 'pam','iso_639_1' => '', 'name' => 'Pampanga; Kapampangan']);
        Language::firstOrCreate(['iso_639_2' => 'pan','iso_639_1' => 'pa', 'name' => 'Panjabi; Punjabi']);
        Language::firstOrCreate(['iso_639_2' => 'pap','iso_639_1' => '', 'name' => 'Papiamento']);
        Language::firstOrCreate(['iso_639_2' => 'pau','iso_639_1' => '', 'name' => 'Palauan']);
        Language::firstOrCreate(['iso_639_2' => 'peo','iso_639_1' => '', 'name' => 'Persian, Old (ca.600-400 B.C.)']);
        Language::firstOrCreate(['iso_639_2' => 'per','iso_639_1' => 'fa', 'name' => 'Persian']);
        Language::firstOrCreate(['iso_639_2' => 'fas','iso_639_1' => 'fa', 'name' => 'Persian']);
        Language::firstOrCreate(['iso_639_2' => 'phi','iso_639_1' => '', 'name' => 'Philippine languages']);
        Language::firstOrCreate(['iso_639_2' => 'phn','iso_639_1' => '', 'name' => 'Phoenician']);
        Language::firstOrCreate(['iso_639_2' => 'pli','iso_639_1' => 'pi', 'name' => 'Pali']);
        Language::firstOrCreate(['iso_639_2' => 'pol','iso_639_1' => 'pl', 'name' => 'Polish']);
        Language::firstOrCreate(['iso_639_2' => 'pon','iso_639_1' => '', 'name' => 'Pohnpeian']);
        Language::firstOrCreate(['iso_639_2' => 'por','iso_639_1' => 'pt', 'name' => 'Portuguese']);
        Language::firstOrCreate(['iso_639_2' => 'pra','iso_639_1' => '', 'name' => 'Prakrit languages']);
        Language::firstOrCreate(['iso_639_2' => 'pro','iso_639_1' => '', 'name' => 'Provencal, Old (to 1500);Occitan, Old (to 1500)']);
        Language::firstOrCreate(['iso_639_2' => 'pus','iso_639_1' => 'ps', 'name' => 'Pushto; Pashto']);
        Language::firstOrCreate(['iso_639_2' => 'qaa','iso_639_1' => '', 'name' => 'Reserved for local use']);
        Language::firstOrCreate(['iso_639_2' => 'que','iso_639_1' => 'qu', 'name' => 'Quechua']);
        Language::firstOrCreate(['iso_639_2' => 'raj','iso_639_1' => '', 'name' => 'Rajasthani']);
        Language::firstOrCreate(['iso_639_2' => 'rap','iso_639_1' => '', 'name' => 'Rapanui']);
        Language::firstOrCreate(['iso_639_2' => 'rar','iso_639_1' => '', 'name' => 'Rarotongan; Cook Islands Maori']);
        Language::firstOrCreate(['iso_639_2' => 'roa','iso_639_1' => '', 'name' => 'Romance languages']);
        Language::firstOrCreate(['iso_639_2' => 'roh','iso_639_1' => 'rm', 'name' => 'Romansh']);
        Language::firstOrCreate(['iso_639_2' => 'rom','iso_639_1' => '', 'name' => 'Romany']);
        Language::firstOrCreate(['iso_639_2' => 'rum','iso_639_1' => 'ro', 'name' => 'Romanian; Moldavian; Moldovan']);
        Language::firstOrCreate(['iso_639_2' => 'ron','iso_639_1' => 'ro', 'name' => 'Romanian; Moldavian; Moldovan']);
        Language::firstOrCreate(['iso_639_2' => 'run','iso_639_1' => 'rn', 'name' => 'Rundi']);
        Language::firstOrCreate(['iso_639_2' => 'rup','iso_639_1' => '', 'name' => 'Aromanian; Arumanian; Macedo-Romanian']);
        Language::firstOrCreate(['iso_639_2' => 'rus','iso_639_1' => 'ru', 'name' => 'Russian']);
        Language::firstOrCreate(['iso_639_2' => 'sad','iso_639_1' => '', 'name' => 'Sandawe']);
        Language::firstOrCreate(['iso_639_2' => 'sag','iso_639_1' => 'sg', 'name' => 'Sango']);
        Language::firstOrCreate(['iso_639_2' => 'sah','iso_639_1' => '', 'name' => 'Yakut']);
        Language::firstOrCreate(['iso_639_2' => 'sai','iso_639_1' => '', 'name' => 'South American Indian languages']);
        Language::firstOrCreate(['iso_639_2' => 'sal','iso_639_1' => '', 'name' => 'Salishan languages']);
        Language::firstOrCreate(['iso_639_2' => 'sam','iso_639_1' => '', 'name' => 'Samaritan Aramaic']);
        Language::firstOrCreate(['iso_639_2' => 'san','iso_639_1' => 'sa', 'name' => 'Sanskrit']);
        Language::firstOrCreate(['iso_639_2' => 'sas','iso_639_1' => '', 'name' => 'Sasak']);
        Language::firstOrCreate(['iso_639_2' => 'sat','iso_639_1' => '', 'name' => 'Santali']);
        Language::firstOrCreate(['iso_639_2' => 'scn','iso_639_1' => '', 'name' => 'Sicilian']);
        Language::firstOrCreate(['iso_639_2' => 'sco','iso_639_1' => '', 'name' => 'Scots']);
        Language::firstOrCreate(['iso_639_2' => 'sel','iso_639_1' => '', 'name' => 'Selkup']);
        Language::firstOrCreate(['iso_639_2' => 'sem','iso_639_1' => '', 'name' => 'Semitic languages']);
        Language::firstOrCreate(['iso_639_2' => 'sga','iso_639_1' => '', 'name' => 'Irish, Old (to 900)']);
        Language::firstOrCreate(['iso_639_2' => 'sgn','iso_639_1' => '', 'name' => 'Sign Languages']);
        Language::firstOrCreate(['iso_639_2' => 'shn','iso_639_1' => '', 'name' => 'Shan']);
        Language::firstOrCreate(['iso_639_2' => 'sid','iso_639_1' => '', 'name' => 'Sidamo']);
        Language::firstOrCreate(['iso_639_2' => 'sin','iso_639_1' => 'si', 'name' => 'Sinhala; Sinhalese']);
        Language::firstOrCreate(['iso_639_2' => 'sio','iso_639_1' => '', 'name' => 'Siouan languages']);
        Language::firstOrCreate(['iso_639_2' => 'sit','iso_639_1' => '', 'name' => 'Sino-Tibetan languages']);
        Language::firstOrCreate(['iso_639_2' => 'sla','iso_639_1' => '', 'name' => 'Slavic languages']);
        Language::firstOrCreate(['iso_639_2' => 'slo','iso_639_1' => 'sk', 'name' => 'Slovak']);
        Language::firstOrCreate(['iso_639_2' => 'slk','iso_639_1' => 'sk', 'name' => 'Slovak']);
        Language::firstOrCreate(['iso_639_2' => 'slv','iso_639_1' => 'sl', 'name' => 'Slovenian']);
        Language::firstOrCreate(['iso_639_2' => 'sma','iso_639_1' => '', 'name' => 'Southern Sami']);
        Language::firstOrCreate(['iso_639_2' => 'sme','iso_639_1' => 'se', 'name' => 'Northern Sami']);
        Language::firstOrCreate(['iso_639_2' => 'smi','iso_639_1' => '', 'name' => 'Sami languages']);
        Language::firstOrCreate(['iso_639_2' => 'smj','iso_639_1' => '', 'name' => 'Lule Sami']);
        Language::firstOrCreate(['iso_639_2' => 'smn','iso_639_1' => '', 'name' => 'Inari Sami']);
        Language::firstOrCreate(['iso_639_2' => 'smo','iso_639_1' => 'sm', 'name' => 'Samoan']);
        Language::firstOrCreate(['iso_639_2' => 'sms','iso_639_1' => '', 'name' => 'Skolt Sami']);
        Language::firstOrCreate(['iso_639_2' => 'sna','iso_639_1' => 'sn', 'name' => 'Shona']);
        Language::firstOrCreate(['iso_639_2' => 'snd','iso_639_1' => 'sd', 'name' => 'Sindhi']);
        Language::firstOrCreate(['iso_639_2' => 'snk','iso_639_1' => '', 'name' => 'Soninke']);
        Language::firstOrCreate(['iso_639_2' => 'sog','iso_639_1' => '', 'name' => 'Sogdian']);
        Language::firstOrCreate(['iso_639_2' => 'som','iso_639_1' => 'so', 'name' => 'Somali']);
        Language::firstOrCreate(['iso_639_2' => 'son','iso_639_1' => '', 'name' => 'Songhai languages']);
        Language::firstOrCreate(['iso_639_2' => 'sot','iso_639_1' => 'st', 'name' => 'Sotho, Southern']);
        Language::firstOrCreate(['iso_639_2' => 'spa','iso_639_1' => 'es', 'name' => 'Spanish; Castilian']);
        Language::firstOrCreate(['iso_639_2' => 'alb','iso_639_1' => 'sq', 'name' => 'Albanian']);
        Language::firstOrCreate(['iso_639_2' => 'sqi','iso_639_1' => 'sq', 'name' => 'Albanian']);
        Language::firstOrCreate(['iso_639_2' => 'srd','iso_639_1' => 'sc', 'name' => 'Sardinian']);
        Language::firstOrCreate(['iso_639_2' => 'srn','iso_639_1' => '', 'name' => 'Sranan Tongo']);
        Language::firstOrCreate(['iso_639_2' => 'srp','iso_639_1' => 'sr', 'name' => 'Serbian']);
        Language::firstOrCreate(['iso_639_2' => 'srr','iso_639_1' => '', 'name' => 'Serer']);
        Language::firstOrCreate(['iso_639_2' => 'ssa','iso_639_1' => '', 'name' => 'Nilo-Saharan languages']);
        Language::firstOrCreate(['iso_639_2' => 'ssw','iso_639_1' => 'ss', 'name' => 'Swati']);
        Language::firstOrCreate(['iso_639_2' => 'suk','iso_639_1' => '', 'name' => 'Sukuma']);
        Language::firstOrCreate(['iso_639_2' => 'sun','iso_639_1' => 'su', 'name' => 'Sundanese']);
        Language::firstOrCreate(['iso_639_2' => 'sus','iso_639_1' => '', 'name' => 'Susu']);
        Language::firstOrCreate(['iso_639_2' => 'sux','iso_639_1' => '', 'name' => 'Sumerian']);
        Language::firstOrCreate(['iso_639_2' => 'swa','iso_639_1' => 'sw', 'name' => 'Swahili']);
        Language::firstOrCreate(['iso_639_2' => 'swe','iso_639_1' => 'sv', 'name' => 'Swedish']);
        Language::firstOrCreate(['iso_639_2' => 'syc','iso_639_1' => '', 'name' => 'Classical Syriac']);
        Language::firstOrCreate(['iso_639_2' => 'syr','iso_639_1' => '', 'name' => 'Syriac']);
        Language::firstOrCreate(['iso_639_2' => 'tah','iso_639_1' => 'ty', 'name' => 'Tahitian']);
        Language::firstOrCreate(['iso_639_2' => 'tai','iso_639_1' => '', 'name' => 'Tai languages']);
        Language::firstOrCreate(['iso_639_2' => 'tam','iso_639_1' => 'ta', 'name' => 'Tamil']);
        Language::firstOrCreate(['iso_639_2' => 'tat','iso_639_1' => 'tt', 'name' => 'Tatar']);
        Language::firstOrCreate(['iso_639_2' => 'tel','iso_639_1' => 'te', 'name' => 'Telugu']);
        Language::firstOrCreate(['iso_639_2' => 'tem','iso_639_1' => '', 'name' => 'Timne']);
        Language::firstOrCreate(['iso_639_2' => 'ter','iso_639_1' => '', 'name' => 'Tereno']);
        Language::firstOrCreate(['iso_639_2' => 'tet','iso_639_1' => '', 'name' => 'Tetum']);
        Language::firstOrCreate(['iso_639_2' => 'tgk','iso_639_1' => 'tg', 'name' => 'Tajik']);
        Language::firstOrCreate(['iso_639_2' => 'tgl','iso_639_1' => 'tl', 'name' => 'Tagalog']);
        Language::firstOrCreate(['iso_639_2' => 'tha','iso_639_1' => 'th', 'name' => 'Thai']);
        Language::firstOrCreate(['iso_639_2' => 'tib','iso_639_1' => 'bo', 'name' => 'Tibetan']);
        Language::firstOrCreate(['iso_639_2' => 'bod','iso_639_1' => 'bo', 'name' => 'Tibetan']);
        Language::firstOrCreate(['iso_639_2' => 'tig','iso_639_1' => '', 'name' => 'Tigre']);
        Language::firstOrCreate(['iso_639_2' => 'tir','iso_639_1' => 'ti', 'name' => 'Tigrinya']);
        Language::firstOrCreate(['iso_639_2' => 'tiv','iso_639_1' => '', 'name' => 'Tiv']);
        Language::firstOrCreate(['iso_639_2' => 'tkl','iso_639_1' => '', 'name' => 'Tokelau']);
        Language::firstOrCreate(['iso_639_2' => 'tlh','iso_639_1' => '', 'name' => 'Klingon; tlhIngan-Hol']);
        Language::firstOrCreate(['iso_639_2' => 'tli','iso_639_1' => '', 'name' => 'Tlingit']);
        Language::firstOrCreate(['iso_639_2' => 'tmh','iso_639_1' => '', 'name' => 'Tamashek']);
        Language::firstOrCreate(['iso_639_2' => 'tog','iso_639_1' => '', 'name' => 'Tonga (Nyasa)']);
        Language::firstOrCreate(['iso_639_2' => 'ton','iso_639_1' => 'to', 'name' => 'Tonga (Tonga Islands)']);
        Language::firstOrCreate(['iso_639_2' => 'tpi','iso_639_1' => '', 'name' => 'Tok Pisin']);
        Language::firstOrCreate(['iso_639_2' => 'tsi','iso_639_1' => '', 'name' => 'Tsimshian']);
        Language::firstOrCreate(['iso_639_2' => 'tsn','iso_639_1' => 'tn', 'name' => 'Tswana']);
        Language::firstOrCreate(['iso_639_2' => 'tso','iso_639_1' => 'ts', 'name' => 'Tsonga']);
        Language::firstOrCreate(['iso_639_2' => 'tuk','iso_639_1' => 'tk', 'name' => 'Turkmen']);
        Language::firstOrCreate(['iso_639_2' => 'tum','iso_639_1' => '', 'name' => 'Tumbuka']);
        Language::firstOrCreate(['iso_639_2' => 'tup','iso_639_1' => '', 'name' => 'Tupi languages']);
        Language::firstOrCreate(['iso_639_2' => 'tur','iso_639_1' => 'tr', 'name' => 'Turkish']);
        Language::firstOrCreate(['iso_639_2' => 'tut','iso_639_1' => '', 'name' => 'Altaic languages']);
        Language::firstOrCreate(['iso_639_2' => 'tvl','iso_639_1' => '', 'name' => 'Tuvalu']);
        Language::firstOrCreate(['iso_639_2' => 'twi','iso_639_1' => 'tw', 'name' => 'Twi']);
        Language::firstOrCreate(['iso_639_2' => 'tyv','iso_639_1' => '', 'name' => 'Tuvinian']);
        Language::firstOrCreate(['iso_639_2' => 'udm','iso_639_1' => '', 'name' => 'Udmurt']);
        Language::firstOrCreate(['iso_639_2' => 'uga','iso_639_1' => '', 'name' => 'Ugaritic']);
        Language::firstOrCreate(['iso_639_2' => 'uig','iso_639_1' => 'ug', 'name' => 'Uighur; Uyghur']);
        Language::firstOrCreate(['iso_639_2' => 'ukr','iso_639_1' => 'uk', 'name' => 'Ukrainian']);
        Language::firstOrCreate(['iso_639_2' => 'umb','iso_639_1' => '', 'name' => 'Umbundu']);
        Language::firstOrCreate(['iso_639_2' => 'und','iso_639_1' => '', 'name' => 'Undetermined']);
        Language::firstOrCreate(['iso_639_2' => 'urd','iso_639_1' => 'ur', 'name' => 'Urdu']);
        Language::firstOrCreate(['iso_639_2' => 'uzb','iso_639_1' => 'uz', 'name' => 'Uzbek']);
        Language::firstOrCreate(['iso_639_2' => 'vai','iso_639_1' => '', 'name' => 'Vai']);
        Language::firstOrCreate(['iso_639_2' => 'ven','iso_639_1' => 've', 'name' => 'Venda']);
        Language::firstOrCreate(['iso_639_2' => 'vie','iso_639_1' => 'vi', 'name' => 'Vietnamese']);
        Language::firstOrCreate(['iso_639_2' => 'vol','iso_639_1' => 'vo', 'name' => 'Volapük']);
        Language::firstOrCreate(['iso_639_2' => 'vot','iso_639_1' => '', 'name' => 'Votic']);
        Language::firstOrCreate(['iso_639_2' => 'wak','iso_639_1' => '', 'name' => 'Wakashan languages']);
        Language::firstOrCreate(['iso_639_2' => 'wal','iso_639_1' => '', 'name' => 'Wolaitta; Wolaytta']);
        Language::firstOrCreate(['iso_639_2' => 'war','iso_639_1' => '', 'name' => 'Waray']);
        Language::firstOrCreate(['iso_639_2' => 'was','iso_639_1' => '', 'name' => 'Washo']);
        Language::firstOrCreate(['iso_639_2' => 'wel','iso_639_1' => 'cy', 'name' => 'Welsh']);
        Language::firstOrCreate(['iso_639_2' => 'cym','iso_639_1' => 'cy', 'name' => 'Welsh']);
        Language::firstOrCreate(['iso_639_2' => 'wen','iso_639_1' => '', 'name' => 'Sorbian languages']);
        Language::firstOrCreate(['iso_639_2' => 'wln','iso_639_1' => 'wa', 'name' => 'Walloon']);
        Language::firstOrCreate(['iso_639_2' => 'wol','iso_639_1' => 'wo', 'name' => 'Wolof']);
        Language::firstOrCreate(['iso_639_2' => 'xal','iso_639_1' => '', 'name' => 'Kalmyk; Oirat']);
        Language::firstOrCreate(['iso_639_2' => 'xho','iso_639_1' => 'xh', 'name' => 'Xhosa']);
        Language::firstOrCreate(['iso_639_2' => 'yao','iso_639_1' => '', 'name' => 'Yao']);
        Language::firstOrCreate(['iso_639_2' => 'yap','iso_639_1' => '', 'name' => 'Yapese']);
        Language::firstOrCreate(['iso_639_2' => 'yid','iso_639_1' => 'yi', 'name' => 'Yiddish']);
        Language::firstOrCreate(['iso_639_2' => 'yor','iso_639_1' => 'yo', 'name' => 'Yoruba']);
        Language::firstOrCreate(['iso_639_2' => 'ypk','iso_639_1' => '', 'name' => 'Yupik languages']);
        Language::firstOrCreate(['iso_639_2' => 'zap','iso_639_1' => '', 'name' => 'Zapotec']);
        Language::firstOrCreate(['iso_639_2' => 'zbl','iso_639_1' => '', 'name' => 'Blissymbols; Blissymbolics; Bliss']);
        Language::firstOrCreate(['iso_639_2' => 'zen','iso_639_1' => '', 'name' => 'Zenaga']);
        Language::firstOrCreate(['iso_639_2' => 'zgh','iso_639_1' => '', 'name' => 'Standard Moroccan Tamazight']);
        Language::firstOrCreate(['iso_639_2' => 'zha','iso_639_1' => 'za', 'name' => 'Zhuang; Chuang']);
        Language::firstOrCreate(['iso_639_2' => 'chi','iso_639_1' => 'zh', 'name' => 'Chinese']);
        Language::firstOrCreate(['iso_639_2' => 'zho','iso_639_1' => 'zh', 'name' => 'Chinese']);
        Language::firstOrCreate(['iso_639_2' => 'znd','iso_639_1' => '', 'name' => 'Zande languages']);
        Language::firstOrCreate(['iso_639_2' => 'zul','iso_639_1' => 'zu', 'name' => 'Zulu']);
        Language::firstOrCreate(['iso_639_2' => 'zun','iso_639_1' => '', 'name' => 'Zuni']);
        Language::firstOrCreate(['iso_639_2' => 'zxx','iso_639_1' => '', 'name' => 'No linguistic content; Not applicable']);
        Language::firstOrCreate(['iso_639_2' => 'zza','iso_639_1' => '', 'name' => 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki']);
    }
}
